"""Generate zabbix/media_type_home_assistant.yaml from the provisioner's constants.

Run after changing the media type: python scripts/generate_media_type.py
"""

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parents[1]))

from custom_components.zabbix_alerts.provisioner import (
    MEDIA_TYPE_NAME,
    MEDIA_TYPE_SCRIPT,
    MESSAGE_TEMPLATES,
    media_type_parameters,
)

OPERATION_MODE = {0: "PROBLEM", 1: "RECOVERY", 2: "UPDATE"}


def _quote(text: str) -> str:
    return "'" + text.replace("'", "''") + "'"


def main() -> None:
    """Write the YAML export."""
    lines = [
        "# Home Assistant webhook media type for Zabbix 7.0+ (manual setup).",
        "# Import under Alerts -> Media types -> Import, then set the Secret",
        "# parameter to the secret shown in the Zabbix integration (Configure ->",
        "# Alerts). Generated by scripts/generate_media_type.py; don't edit by hand.",
        "zabbix_export:",
        "  version: '7.0'",
        "  media_types:",
        f"    - name: {_quote(MEDIA_TYPE_NAME.replace(' (ha-zabbix-alerts)', ''))}",
        "      type: WEBHOOK",
        "      parameters:",
    ]
    for order, parameter in enumerate(media_type_parameters("<secret>")):
        lines += [
            f"        - sortorder: '{order}'",
            f"          name: {parameter['name']}",
            f"          value: {_quote(parameter['value'])}",
        ]
    lines += ["      script: |"]
    lines += [
        f"        {line}" if line else "" for line in MEDIA_TYPE_SCRIPT.splitlines()
    ]
    lines += [
        "      timeout: 30s",
        "      description: 'Sends Zabbix problem alerts to Home Assistant (ha-zabbix).'",
        "      message_templates:",
    ]
    for template in MESSAGE_TEMPLATES:
        lines += [
            "        - event_source: TRIGGERS",
            f"          operation_mode: {OPERATION_MODE[int(template['recovery'])]}",
            f"          subject: {_quote(str(template['subject']))}",
            f"          message: {_quote(str(template['message']))}",
        ]
    path = Path(__file__).parents[1] / "zabbix" / "media_type_home_assistant.yaml"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
